// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// crawlerDao is the data access object for the table hg_crawler.
// You can define custom methods on it to extend its functionality as needed.
type crawlerDao struct {
	*internal.CrawlerDao
}

var (
	// Crawler is a globally accessible object for table hg_crawler operations.
	Crawler = crawlerDao{internal.NewCrawlerDao()}
)

// Add your custom methods and functionality below.
