// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// internalTgstatChannelCrawlerUrlDao is internal type for wrapping internal DAO implements.
type internalTgstatChannelCrawlerUrlDao = *internal.TgstatChannelCrawlerUrlDao

// tgstatChannelCrawlerUrlDao is the data access object for table hg_tgstat_channel_crawler_url.
// You can define custom methods on it to extend its functionality as you wish.
type tgstatChannelCrawlerUrlDao struct {
	internalTgstatChannelCrawlerUrlDao
}

var (
	// TgstatChannelCrawlerUrl is globally public accessible object for table hg_tgstat_channel_crawler_url operations.
	TgstatChannelCrawlerUrl = tgstatChannelCrawlerUrlDao{
		internal.NewTgstatChannelCrawlerUrlDao(),
	}
)

// Fill with you ideas below.
