// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// tgstatChannelDao is the data access object for the table hg_tgstat_channel.
// You can define custom methods on it to extend its functionality as needed.
type tgstatChannelDao struct {
	*internal.TgstatChannelDao
}

var (
	// TgstatChannel is a globally accessible object for table hg_tgstat_channel operations.
	TgstatChannel = tgstatChannelDao{internal.NewTgstatChannelDao()}
)

// Add your custom methods and functionality below.
